# Dot Product

In [ ]:
import numpy as np

print(np.dot(10, 5))

In [ ]:
a = np.array([2, 4], np.uint8)
b = np.array([5, 6], np.uint8)

print(np.dot(a, b))

In [ ]:
a = np.array([[2, 4], [5, 8]], np.uint8)
b = np.array([[5, 6], [9, 3]], np.uint8)

print(np.dot(a, b))

In [ ]:
a = np.random.rand(10, 5)
b = np.random.rand(5, 2)
c = np.random.rand(2, 3)
d = np.random.rand(3, 4)

e = np.linalg.multi_dot([a, b, c, d])
print(e)


# Vector Dot Product

In [5]:
a = np.array ([1, 2])
b = np.array ([3, 4])

print(np.vdot(a, b))

11


In [6]:
a = np.array ([1 + 5j, 2 + 3j])
b = np.array ([3 + 2j, 4 + 7j])

print(np.vdot(a, b))

(42-11j)


In [7]:
print(np.vdot(b, a))

(42+11j)


# Inner Product

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([0, 1, 0, 1, 0, 1])

print(np.inner(a, b))

12


In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[0, 1, 0], [1, 0, 1]])

print(np.inner(a, b))

[[ 2  4]
 [ 5 10]]


# QR Decomposition

In [11]:
a = np.random.rand(3, 3)
print(a)

[[0.53946039 0.71357161 0.13546173]
 [0.41274675 0.75412655 0.46267726]
 [0.18045161 0.05626532 0.6183973 ]]


In [14]:
q, r = np.linalg.qr(a)
print('q = ', q, '\n\nr = ', r, '\n')

print(np.dot(q, r))

q =  [[-0.76757776  0.21735149 -0.6029782 ]
 [-0.58728172 -0.61534322  0.52578788]
 [-0.25675777  0.75770116  0.59997033]] 

r =  [[-0.70280877 -1.005053   -0.53447762]
 [ 0.         -0.26631851  0.21329785]
 [ 0.          0.          0.53260966]] 

[[0.53946039 0.71357161 0.13546173]
 [0.41274675 0.75412655 0.46267726]
 [0.18045161 0.05626532 0.6183973 ]]


# Determinant and Solving Linear Equations

In [15]:
a = np.array([[5, 6], [3, 4]])

print(np.linalg.det(a))

1.9999999999999971


In [16]:
a = np.array([[2, 1, -3 ], [4, -2, 1], [3, 5, -2]], np.int16)
b = np.array([-4, 9, 5], np.int16)

# ax = b

x = np.linalg.solve(a, b)
print(x)

[2. 1. 3.]
