In [3]:
import numpy as np
import scipy.linalg

x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

print("\n", scipy.linalg.inv(x))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

 [[-4.50359963e+15  9.00719925e+15 -4.50359963e+15]
 [ 9.00719925e+15 -1.80143985e+16  9.00719925e+15]
 [-4.50359963e+15  9.00719925e+15 -4.50359963e+15]]


In [5]:
# ax = b
a = np.array([[2, 1, -3], [4, -2, 1], [3, 5, -2]])
b = np.array([-4, 9, 5])

print(scipy.linalg.solve(a, b))

[2. 1. 3.]


In [7]:
a = np.array([[0, 2, 3], [4, 5, 6], [7, 8, 9]])
print(scipy.linalg.det(a))

3.0


In [8]:
print(scipy.linalg.norm(a))

16.852299546352718


In [9]:
a = np.arange(36).reshape((6, 6))
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [10]:
print(scipy.linalg.tril(a, k=0))

[[ 0  0  0  0  0  0]
 [ 6  7  0  0  0  0]
 [12 13 14  0  0  0]
 [18 19 20 21  0  0]
 [24 25 26 27 28  0]
 [30 31 32 33 34 35]]


In [11]:
print(scipy.linalg.tril(a, k=-1))

[[ 0  0  0  0  0  0]
 [ 6  0  0  0  0  0]
 [12 13  0  0  0  0]
 [18 19 20  0  0  0]
 [24 25 26 27  0  0]
 [30 31 32 33 34  0]]


In [12]:
print(scipy.linalg.tril(a, k=2))

[[ 0  1  2  0  0  0]
 [ 6  7  8  9  0  0]
 [12 13 14 15 16  0]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


In [13]:
print(scipy.linalg.triu(a, k=0))

[[ 0  1  2  3  4  5]
 [ 0  7  8  9 10 11]
 [ 0  0 14 15 16 17]
 [ 0  0  0 21 22 23]
 [ 0  0  0  0 28 29]
 [ 0  0  0  0  0 35]]


In [14]:
print(scipy.linalg.triu(a, k=-2))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [ 0 19 20 21 22 23]
 [ 0  0 26 27 28 29]
 [ 0  0  0 33 34 35]]


In [15]:
print(scipy.linalg.triu(a, k=1))

[[ 0  1  2  3  4  5]
 [ 0  0  8  9 10 11]
 [ 0  0  0 15 16 17]
 [ 0  0  0  0 22 23]
 [ 0  0  0  0  0 29]
 [ 0  0  0  0  0  0]]


In [16]:
a = np.arange(49).reshape((7, 7))
print(a)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]


In [17]:
p, l, u = scipy.linalg.lu(a)
# permutation matrix
print(p)
print(l)
print(u)

[[0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]
[[ 1.          0.          0.          0.          0.          0.
   0.        ]
 [ 0.          1.          0.          0.          0.          0.
   0.        ]
 [ 0.83333333  0.16666667  1.          0.          0.          0.
   0.        ]
 [ 0.5         0.5        -0.          1.          0.          0.
   0.        ]
 [ 0.66666667  0.33333333  0.5         0.          1.          0.
   0.        ]
 [ 0.33333333  0.66666667  0.25        0.          0.          1.
   0.        ]
 [ 0.16666667  0.83333333  0.125       0.          0.          0.
   1.        ]]
[[ 4.20000000e+01  4.30000000e+01  4.40000000e+01  4.50000000e+01
   4.60000000e+01  4.70000000e+01  4.80000000e+01]
 [ 0.00000000e+00  1.00000000e+00  2.00000000e+00  3.00000000e+00
   4.00000000e+00  5.00000000e+00  6.00000000e+00]
 [ 0.00000000e+00  0.00000000

In [18]:
a = np.arange(9).reshape((3, 3))
q, r = scipy.linalg.qr(a)
print(q)
print(r)

[[ 0.         -0.91287093  0.40824829]
 [ 0.4472136  -0.36514837 -0.81649658]
 [ 0.89442719  0.18257419  0.40824829]]
[[ 6.70820393e+00  8.04984472e+00  9.39148551e+00]
 [ 0.00000000e+00 -1.09544512e+00 -2.19089023e+00]
 [ 0.00000000e+00  0.00000000e+00  1.33226763e-15]]


In [19]:
q, r = scipy.linalg.rq(a)
print(q)
print(r)

[[ 4.44089210e-16  1.20402011e+00 -1.88423342e+00]
 [ 0.00000000e+00  6.02010056e-01 -7.04539452e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.22065556e+01]]
[[ 0.40824829 -0.81649658  0.40824829]
 [-0.76923507 -0.06689001  0.63545506]
 [-0.49153915 -0.57346234 -0.65538554]]
