# Reading the data from a CSV file

In [1]:
import numpy as np
data = np.loadtxt('data.csv', delimiter=',')
print(data)

[[  0.   1.  18.   2.]
 [  1.   6.   1.   3.]
 [  2.   3. 154.   0.]
 [  4. 978.   3.   6.]
 [  5.   2.  41.  45.]
 [  6.  67.   2.   3.]
 [  7.   5.  67.   2.]]


In [2]:
print(type(data))

<class 'numpy.ndarray'>


In [3]:
data = np.loadtxt('data.csv', delimiter=',',
                 skiprows=3, usecols=[1, 3]) 
print(data)

[[978.   6.]
 [  2.  45.]
 [ 67.   3.]
 [  5.   2.]]
